import type { WorkflowTemplate } from "@/types";
import { CARD_DEFAULTS, sizeFromRatio } from "@/shared/constants";

export const WORKFLOW_TEMPLATES: WorkflowTemplate[] = [
  {
    id: "wf-ai-chat",
    name: "AI 对话",
    description: "输入提示词，一键生成文字内容",
    icon: "MessageSquare",
    category: "chat",
    cards: [
      {
        type: "ai_chat",
        title: "生成文字",
        relativeX: 0,
        relativeY: 0,
        ...CARD_DEFAULTS.ai_chat,
      },
    ],
  },
  {
    id: "wf-chat-chain",
    name: "对话链",
    description: "上一个 AI 的输出作为下一个的上下文，逐步精炼内容",
    icon: "MessageSquare",
    category: "chat",
    cards: [
      {
        type: "ai_chat",
        title: "初稿",
        relativeX: 0,
        relativeY: 0,
        width: CARD_DEFAULTS.ai_chat.width,
        height: CARD_DEFAULTS.ai_chat.height,
        data: { content: "", result: "" },
      },
      {
        type: "ai_chat",
        title: "润色",
        relativeX: CARD_DEFAULTS.ai_chat.width + 60,
        relativeY: 0,
        width: CARD_DEFAULTS.ai_chat.width,
        height: CARD_DEFAULTS.ai_chat.height,
        data: { content: "请基于上游内容进行润色优化", result: "" },
      },
    ],
    connections: [{ sourceIndex: 0, targetIndex: 1 }],
  },
  {
    id: "wf-ai-image",
    name: "AI 图片生成",
    description: "通过文字描述，一键生成高质量 AI 图片",
    icon: "ImageIcon",
    category: "image",
    cards: [
      {
        type: "ai_image",
        title: "AI 图片生成",
        relativeX: 0,
        relativeY: 0,
        ...CARD_DEFAULTS.ai_image,
      },
    ],
  },
  {
    id: "wf-content-plan",
    name: "内容策划",
    description: "AI 辅助制定内容策略，生成系列文案与配图方案",
    icon: "Layers",
    category: "composite",
    cards: [
      {
        type: "ai_chat",
        title: "内容策划",
        relativeX: 0,
        relativeY: 0,
        width: CARD_DEFAULTS.ai_chat.width,
        height: CARD_DEFAULTS.ai_chat.height,
        data: {
          content: "请帮我制定一套完整的内容营销策划方案，包括主题、文案方向和配图建议。",
          result: "",
        },
      },
      {
        type: "text",
        title: "策划备注",
        relativeX: CARD_DEFAULTS.ai_chat.width + 40,
        relativeY: 0,
        ...CARD_DEFAULTS.text,
      },
    ],
  },
  {
    id: "wf-white-bg",
    name: "一键白底图",
    description: "上传商品图，AI 自动识别特征并生成白底精修图和多角度展示图",
    icon: "ImageIcon",
    category: "composite",
    cards: [
      {
        type: "ai_image",
        title: "商品原图",
        relativeX: 0,
        relativeY: CARD_DEFAULTS.ai_chat.height + 30 - sizeFromRatio(1).height / 2,
        ...sizeFromRatio(1),
        data: { content: "", size: "1:1" },
      },
      {
        type: "ai_chat",
        title: "服装特征识别",
        relativeX: sizeFromRatio(1).width + 80,
        relativeY: 0,
        width: CARD_DEFAULTS.ai_chat.width,
        height: CARD_DEFAULTS.ai_chat.height,
        data: {
          _locked: true,
          _label: "服装特征识别",
          _description: "接收商品原图后点击分析",
          _systemPrompt: [
            "你是一个电商服装产品精修提示词生成专家。用户会上传服装图片，你需要：",
            "1. 识别图片中的服装品类（如牛仔裤、羽绒服、衬衣、马甲等）",
            "2. 识别服装颜色（如浅蓝色、米白色、深灰色等）",
            "3. 识别服装关键特征（如水洗做旧、菱格绗缝、亚麻纹理、纽扣细节、刺绣图案等）",
            "4. 识别版型细节（如阔腿版型、宽松版型、常规合身等）",
            "",
            "基于识别到的信息，按照以下模板生成标准化精修提示词。只输出提示词本身，不要输出任何其他内容：",
            "",
            "产品精修，将图片中的[颜色][服装品类]完整提取并转换成3D立体形状，置于纯净的纯白背景上。正面视图、背面视图，平视视角，精准还原[服装品类]的颜色、[关键特征1]、[关键特征2]、[设计细节]以及领标细节，去除多余褶皱，使衣身轮廓平整顺滑，边缘干净无杂色。清除灰尘、瑕疵，让[服装品类]看起来挺括、崭新、洁净，光线均匀无杂乱阴影，符合电商主图标准，主体突出。",
          ].join("\n"),
          content: "请分析上传的服装图片，识别服装的品类、颜色和关键特征，生成电商白底精修提示词。",
          result: "",
        },
      },
      {
        type: "ai_image",
        title: "白底精修图",
        relativeX: sizeFromRatio(1).width + 80 + CARD_DEFAULTS.ai_chat.width + 80,
        relativeY: CARD_DEFAULTS.ai_chat.height + 30 - sizeFromRatio(1).height / 2,
        ...sizeFromRatio(1),
        data: { content: "", size: "1:1" },
      },
      {
        type: "ai_chat",
        title: "多角度提示词生成",
        relativeX: sizeFromRatio(1).width + 80 + CARD_DEFAULTS.ai_chat.width + 80 + sizeFromRatio(1).width + 80,
        relativeY: 0,
        width: CARD_DEFAULTS.ai_chat.width,
        height: CARD_DEFAULTS.ai_chat.height,
        data: {
          _locked: true,
          _label: "多角度提示词生成",
          _description: "基于白底图自动生成多角度展示提示词",
          _systemPrompt: [
            "你是一个电商服装多角度展示图提示词生成专家。用户会提供一张服装图片，你需要：",
            "",
            "1. 识别图片中的服装品类、颜色、关键特征",
            "2. 基于以下模板生成多角度展示图提示词。只输出提示词本身，不要输出任何其他内容：",
            "",
            "基于我提供的这件[颜色][服装品类]原图，生成一组多角度产品细节特征展示图。要求保持[服装品类]的款式、[颜色]、[关键纹理/设计]、[版型/细节]等所有细节完全不变，仅从不同角度（正面、侧面、背面、45度角、[关键部位特写1]、[关键部位特写2]、[细节特写1]、[细节特写2]等）进行拍摄式呈现，不要有重复的角度呈现。整体风格为简洁的白底商业产品图，光线均匀柔和，突出质感，清晰展现[面料质感]与[版型]细节。",
          ].join("\n"),
          content: "请分析这张服装图片，识别服装特征，生成多角度展示图提示词。",
          result: "",
        },
      },
      {
        type: "ai_image",
        title: "多角度展示图",
        relativeX: sizeFromRatio(1).width + 80 + CARD_DEFAULTS.ai_chat.width + 80 + sizeFromRatio(1).width + 80 + CARD_DEFAULTS.ai_chat.width + 80,
        relativeY: CARD_DEFAULTS.ai_chat.height + 30 - sizeFromRatio(16 / 9).height / 2,
        ...sizeFromRatio(16 / 9),
        data: { content: "", size: "16:9" },
      },
    ],
    connections: [
      { sourceIndex: 0, targetIndex: 1 },
      { sourceIndex: 0, targetIndex: 2 },
      { sourceIndex: 1, targetIndex: 2 },
      { sourceIndex: 2, targetIndex: 3 },
      { sourceIndex: 2, targetIndex: 4 },
      { sourceIndex: 3, targetIndex: 4 },
    ],
  },
  {
    id: "wf-tryon",
    name: "模特换装",
    description: "上传模特图与服装图，AI 自动将服装穿在模特身上，保留姿态与背景",
    icon: "Shirt",
    category: "composite",
    cards: [
      {
        type: "ai_image",
        title: "模特图",
        relativeX: 0,
        relativeY: CARD_DEFAULTS.ai_chat.height + 30 - sizeFromRatio(1).height - 15,
        ...sizeFromRatio(1),
        data: { content: "", size: "1:1" },
      },
      {
        type: "ai_image",
        title: "服装图",
        relativeX: 0,
        relativeY: CARD_DEFAULTS.ai_chat.height + 45,
        ...sizeFromRatio(1),
        data: { content: "", size: "1:1" },
      },
      {
        type: "ai_image",
        title: "模特换装",
        relativeX: sizeFromRatio(1).width + 80,
        relativeY: CARD_DEFAULTS.ai_chat.height + 30 - sizeFromRatio(3 / 4).height / 2,
        ...sizeFromRatio(3 / 4),
        data: {
          _locked: true,
          _label: "模特换装",
          _description: "将模特图穿上服装图，姿态/背景保持不变",
          content: [
            "请将第一张参考图（模特图）中的人物穿上第二张参考图（服装图）展示的服装。",
            "严格保持人物的姿态、面部特征、肤色、发型与原始背景完全不变；",
            "仅替换身上的服装，确保新服装的款式、颜色、图案、纹理细节与版型与服装图完全一致；",
            "服装的穿着效果要符合人体结构与透视，光影自然过渡，整体真实协调。",
          ].join("\n"),
          size: "3:4",
        },
      },
    ],
    connections: [
      { sourceIndex: 0, targetIndex: 2 },
      { sourceIndex: 1, targetIndex: 2 },
    ],
  },
  {
    id: "wf-face-gen",
    name: "捏脸",
    description: "上传人脸照片，AI 融合生成人脸肖像和 4 角度人物展示",
    icon: "User",
    category: "composite",
    cards: [
      {
        type: "ai_image",
        title: "人脸照片1",
        relativeX: 0,
        relativeY: CARD_DEFAULTS.ai_chat.height + 30 - sizeFromRatio(1).height - 15,
        ...sizeFromRatio(1),
        data: { content: "", size: "1:1" },
      },
      {
        type: "ai_image",
        title: "人脸照片2",
        relativeX: 0,
        relativeY: CARD_DEFAULTS.ai_chat.height + 45,
        ...sizeFromRatio(1),
        data: { content: "", size: "1:1" },
      },
      {
        type: "ai_chat",
        title: "人脸特征分析",
        relativeX: sizeFromRatio(1).width + 80,
        relativeY: 0,
        width: CARD_DEFAULTS.ai_chat.width,
        height: CARD_DEFAULTS.ai_chat.height,
        data: {
          _locked: true,
          _label: "人脸特征分析",
          _description: "接收两张人脸照片后点击分析",
          _systemPrompt: [
            "你是一个人脸特征分析与融合提示词生成专家。用户会上传两张人脸照片，你需要：",
            "",
            "1. 分析每张照片中的面部特征（脸型、眼型、鼻型、嘴型、肤色、发型等）",
            "2. 识别两张面孔的独特特征和共同特征",
            "3. 基于分析结果，生成一段融合两张面孔特征的肖像生成提示词",
            "",
            "只输出提示词本身，不要输出任何其他内容。提示词模板：",
            "",
            "A photorealistic portrait of a distinct individual who looks like the biological offspring of the people in the provided reference photos.",
            "The face should be a natural, organic blend of the input features — combining [面孔1关键特征] with [面孔2关键特征],",
            "creating a unique new identity that bears a strong family resemblance to both inputs without being a direct copy of either.",
            "Capture the subtle genetic traits from the references.",
            "",
            "Character Description:",
            "Subject: An Asian model with [融合后肤色], [融合后脸型], [融合后眼型], [融合后鼻型], [融合后嘴型], and [融合后发型].",
            "Flawless, pore-level skin texture.",
            "Expression: Neutral and candid, with a high-quality photo realism aesthetic — soft, cinematic lighting that highlights facial contours.",
            "Vibe: High-fashion, sophisticated, and authentic.",
            "Setting: white background, eye-level front face.",
            "",
            "Technical Constraints:",
            "Maintain consistent lighting across the blended features.",
            "Output in 4k resolution, raw photography style.",
          ].join("\n"),
          content: "请分析上传的两张人脸照片，识别面部特征，生成人脸融合肖像提示词。",
          result: "",
        },
      },
      {
        type: "ai_image",
        title: "人脸肖像融合",
        relativeX: sizeFromRatio(1).width + 80 + CARD_DEFAULTS.ai_chat.width + 80,
        relativeY: CARD_DEFAULTS.ai_chat.height + 30 - sizeFromRatio(3 / 4).height / 2,
        ...sizeFromRatio(3 / 4),
        data: { content: "", size: "9:16" },
      },
      {
        type: "ai_chat",
        title: "多角度提示词生成",
        relativeX: sizeFromRatio(1).width + 80 + CARD_DEFAULTS.ai_chat.width + 80 + sizeFromRatio(3 / 4).width + 80,
        relativeY: 0,
        width: CARD_DEFAULTS.ai_chat.width,
        height: CARD_DEFAULTS.ai_chat.height,
        data: {
          _locked: true,
          _label: "多角度提示词生成",
          _description: "基于融合肖像自动生成 4 角度展示提示词",
          _systemPrompt: [
            "你是一个人物多角度展示图提示词生成专家。用户会提供一张人脸肖像图片，你需要：",
            "",
            "1. 识别图片中人物的面部特征、发型、肤色等关键视觉特征",
            "2. 基于以下模板生成多角度展示图提示词。只输出提示词本身，不要输出任何其他内容：",
            "",
            "A 2x2 grid character sheet of the reference image, white background.",
            "The grid shows the same character from 4 different camera angles:",
            "1. Front view, 2. Left Profile view, 3. Right Three-Quarter view, 4. Low angle looking up.",
            "Headshot framing. Consistent facial features including [肤色], [脸型], [眼型], [发型] and all distinguishing characteristics.",
            "Maintain identical lighting and style across all angles.",
          ].join("\n"),
          content: "请分析这张人脸肖像，生成 4 角度展示图提示词。",
          result: "",
        },
      },
      {
        type: "ai_image",
        title: "4角度展示",
        relativeX: sizeFromRatio(1).width + 80 + CARD_DEFAULTS.ai_chat.width + 80 + sizeFromRatio(3 / 4).width + 80 + CARD_DEFAULTS.ai_chat.width + 80,
        relativeY: CARD_DEFAULTS.ai_chat.height + 30 - sizeFromRatio(16 / 9).height / 2,
        ...sizeFromRatio(16 / 9),
        data: { content: "", size: "16:9" },
      },
    ],
    connections: [
      { sourceIndex: 0, targetIndex: 2 },
      { sourceIndex: 1, targetIndex: 2 },
      { sourceIndex: 0, targetIndex: 3 },
      { sourceIndex: 1, targetIndex: 3 },
      { sourceIndex: 2, targetIndex: 3 },
      { sourceIndex: 3, targetIndex: 4 },
      { sourceIndex: 3, targetIndex: 5 },
      { sourceIndex: 4, targetIndex: 5 },
    ],
  },
  {
    id: "wf-scene-replace",
    name: "场景替换",
    description: "上传人物图与场景图，AI 将人物完美融入新场景，保留服装与光影一致性",
    icon: "Mountain",
    category: "composite",
    cards: [
      {
        type: "ai_image",
        title: "人物图",
        relativeX: 0,
        relativeY: CARD_DEFAULTS.ai_chat.height + 30 - sizeFromRatio(1).height - 15,
        ...sizeFromRatio(1),
        data: { content: "", size: "1:1" },
      },
      {
        type: "ai_image",
        title: "场景图",
        relativeX: 0,
        relativeY: CARD_DEFAULTS.ai_chat.height + 45,
        ...sizeFromRatio(1),
        data: { content: "", size: "1:1" },
      },
      {
        type: "ai_chat",
        title: "场景融合提示词",
        relativeX: sizeFromRatio(1).width + 80,
        relativeY: CARD_DEFAULTS.ai_chat.height / 2 + 30,
        width: CARD_DEFAULTS.ai_chat.width,
        height: CARD_DEFAULTS.ai_chat.height,
        data: {
          _locked: true,
          _label: "场景融合提示词",
          _description: "分析人物图与场景图，生成商业摄影级场景融合提示词",
          _systemPrompt: [
            "你是一个商业摄影场景融合提示词生成专家。用户会上传两张图片：",
            "- 图1（人物图）：包含人物形象和全套服装",
            "- 图2（场景图）：包含目标场景环境",
            "",
            "你需要：",
            "1. 分析图1中的人物面部特征、服装品类、颜色、材质、版型等所有服装细节",
            "2. 分析图1中的背景和环境元素",
            "3. 分析图2中的场景环境、光影特征、色温、景深、镜头焦段",
            "4. 分析图2中原人物的动作状态和姿态（如果有人物）",
            "",
            "基于分析结果，按照以下模板生成最终提示词。请将所有方括号中的描述替换为具体的分析结果。只输出提示词本身，不要输出任何其他内容：",
            "",
            "这是一张极度写实的商业摄影大片。请以侧边参考图 1（Image 1）中的人物形象和全套服装为核心主体，将其完美平移并融入到参考图 2（Image 2）的环境。",
            "1. 场景继承：人物所处的环境完全继承自图2，必须精准保留 [描述图2背景的具体元素]。",
            "2. 人物与动作继承：替换后的人物必须精准继承图1中的 [描述图1的服装及面部特征]。人物的姿态必须完美复刻图2原人物的 [描述图2的动作状态]。",
            "3. 物理光影融合（核心）：人物的全身光影必须受到图2环境的 [描述图2的光影特征，如：暖色调侧逆光/散射日光] 物理约束。皮肤纹理、布料反光和阴影边缘必须与图2的光源方向及色温完全匹配，消除一切抠图感。",
            "4. 场景稳定性：严禁改变图2背景中的任何细节，包括 [描述图2特有背景元素，如：面包店招牌、地板纹理]。保持与图2一致的浅景深和镜头焦段。",
            "画质要求：8K超清，电影级胶片质感，商业后期质感，极致细节。",
          ].join("\n"),
          content: "请分析上传的人物图（图1）和场景图（图2），识别人物服装特征、场景环境特征和光影条件，生成商业摄影级别的场景融合提示词。",
          result: "",
        },
      },
      {
        type: "ai_image",
        title: "场景替换",
        relativeX: sizeFromRatio(1).width + 80 + CARD_DEFAULTS.ai_chat.width + 80,
        relativeY: CARD_DEFAULTS.ai_chat.height + 30 - sizeFromRatio(3 / 4).height / 2,
        ...sizeFromRatio(3 / 4),
        data: {
          _locked: true,
          _label: "场景替换",
          _description: "基于融合提示词与参考图生成最终合成图",
          content: "",
          size: "3:4",
        },
      },
    ],
    connections: [
      { sourceIndex: 0, targetIndex: 2 },
      { sourceIndex: 1, targetIndex: 2 },
      { sourceIndex: 0, targetIndex: 3 },
      { sourceIndex: 1, targetIndex: 3 },
      { sourceIndex: 2, targetIndex: 3 },
    ],
  },
  {
    id: "wf-pose-fission",
    name: "模特姿态裂变",
    description: "上传模特人物图，AI 保持面部与服装不变，裂变生成多种姿态变体",
    icon: "PersonStanding",
    category: "composite",
    cards: [
      {
        type: "ai_image",
        title: "人物图",
        relativeX: 0,
        relativeY: 0,
        ...sizeFromRatio(3 / 4),
        data: { content: "", size: "3:4" },
      },
      {
        type: "ai_image",
        title: "姿态裂变",
        relativeX: sizeFromRatio(3 / 4).width + 80,
        relativeY: (sizeFromRatio(3 / 4).height - sizeFromRatio(16 / 9).height) / 2,
        ...sizeFromRatio(16 / 9),
        data: {
          _locked: true,
          _label: "姿态裂变",
          _description: "保持人物面部和服装，生成 4 种不同姿态",
          content: [
            "保持参考图中人物面部和服装不变，环境不变。",
            "生成4张不同的人物姿态图：",
            "第一张全身站立，第二张半身特写，第三张坐在路边长椅，第四张服装特写。",
            "保持服装细节，超写实，高细节，lookbook质感，不要出现人物黑边。",
          ].join("\n"),
          size: "16:9",
        },
      },
    ],
    connections: [{ sourceIndex: 0, targetIndex: 1 }],
  },
  {
    id: "wf-face-merge",
    name: "人脸合成",
    description: "上传两张人物照片，AI 融合面部特征生成全新写实人像，支持切换男/女",
    icon: "ScanFace",
    category: "composite",
    cards: [
      {
        type: "ai_image",
        title: "人物1",
        relativeX: 0,
        relativeY: 0,
        ...sizeFromRatio(1),
        data: { content: "", size: "1:1" },
      },
      {
        type: "ai_image",
        title: "人物2",
        relativeX: 0,
        relativeY: sizeFromRatio(1).height + 60,
        ...sizeFromRatio(1),
        data: { content: "", size: "1:1" },
      },
      {
        type: "ai_image",
        title: "人脸合成",
        relativeX: sizeFromRatio(1).width + 80,
        relativeY: (sizeFromRatio(1).height + 60) / 2,
        ...sizeFromRatio(1),
        data: {
          _locked: true,
          _label: "人脸合成",
          _description: "融合两张人脸生成全新写实人像，可切换性别",
          _params: { gender: "女" },
          _promptTemplate: [
            "A photorealistic portrait of a distinct individual who looks like the biological offspring of the people in the provided reference photos.",
            "The face should be a natural, organic blend of the input features, creating a unique new identity that bears a strong family resemblance to both inputs without being a direct copy of either.",
            "Capture the subtle genetic traits from the references.",
            "",
            "Character Description:",
            "Subject: An Asian [{{gender}}] model with flawless, pore-level skin texture.",
            "Expression: Neutral and candid, with a high-quality photo realism aesthetic — soft, cinematic lighting that highlights facial contours.",
            "Vibe: High-fashion, sophisticated, and authentic.",
            "Setting: white background, eye-level front face.",
            "",
            "Technical Constraints:",
            "Maintain consistent lighting across the blended features.",
            "Output in 4k resolution, raw photography style.",
          ].join("\n"),
          content: [
            "A photorealistic portrait of a distinct individual who looks like the biological offspring of the people in the provided reference photos.",
            "The face should be a natural, organic blend of the input features, creating a unique new identity that bears a strong family resemblance to both inputs without being a direct copy of either.",
            "Capture the subtle genetic traits from the references.",
            "",
            "Character Description:",
            "Subject: An Asian [女] model with flawless, pore-level skin texture.",
            "Expression: Neutral and candid, with a high-quality photo realism aesthetic — soft, cinematic lighting that highlights facial contours.",
            "Vibe: High-fashion, sophisticated, and authentic.",
            "Setting: white background, eye-level front face.",
            "",
            "Technical Constraints:",
            "Maintain consistent lighting across the blended features.",
            "Output in 4k resolution, raw photography style.",
          ].join("\n"),
          size: "1:1",
        },
      },
    ],
    connections: [
      { sourceIndex: 0, targetIndex: 2 },
      { sourceIndex: 1, targetIndex: 2 },
    ],
  },
  {
    id: "wf-look-fission",
    name: "Look全身裂变",
    description: "上传模特图，AI 锁定机位构图，仅变化姿势生成多组 Lookbook 风格变体",
    icon: "PersonStanding",
    category: "composite",
    cards: [
      {
        type: "ai_image",
        title: "人物图",
        relativeX: 0,
        relativeY: (CARD_DEFAULTS.ai_chat.height - sizeFromRatio(3 / 4).height) / 2,
        ...sizeFromRatio(3 / 4),
        data: { content: "", size: "3:4" },
      },
      {
        type: "ai_chat",
        title: "姿势灵感生成",
        relativeX: sizeFromRatio(3 / 4).width + 80,
        relativeY: 0,
        width: CARD_DEFAULTS.ai_chat.width,
        height: CARD_DEFAULTS.ai_chat.height,
        data: {
          _locked: true,
          _label: "姿势灵感生成",
          _description: "分析人物图，生成 5 组锁定机位的姿势变化提示词",
          _systemPrompt: [
            "你是一个商业摄影姿势灵感提示词生成专家。用户会上传一张模特图像，你需要：",
            "",
            "1. 分析图中模特的服装、面部特征、体型、场景、机位角度、构图比例",
            "2. 基于以下要求生成 5 组姿势变化提示词",
            "",
            "【最高优先级 · 强制锁定规则】",
            "1. 机位必须完全锁定：拍摄角度不变、镜头视角不变、相机高度不变",
            "2. 构图必须完全一致：模特在画面中的位置不变、人物大小比例不变、头身比例/腿长比例完全一致",
            "3. 严禁扩图：画布尺寸不变、不新增画面内容、不补边/不拉伸/不裁切",
            "4. 模特身份必须一致：面部/发型/体型/气质保持完全一致、服装保持100%一致（颜色/版型/材质/褶皱逻辑）",
            "",
            "【唯一允许变化的内容：动作（小幅度）】",
            "- 角色姿态：请随机设计全新的、符合商业摄影美感的人体姿势",
            "- 动作变化必须符合真实人体力学",
            "",
            "【整体风格】",
            "真实商业摄影 / 电商模特 / Lookbook 风格",
            "自然、克制、专业",
            "",
            "最终只生成适合出图的中文提示词，按灵感1、灵感2、灵感3、灵感4、灵感5的格式输出，不解释。",
          ].join("\n"),
          content: "请分析上传的模特图像，基于锁定机位和构图的要求，生成 5 组小幅度姿势变化的 Lookbook 风格提示词。",
          result: "",
        },
      },
      {
        type: "ai_image",
        title: "全身裂变",
        relativeX: sizeFromRatio(3 / 4).width + 80 + CARD_DEFAULTS.ai_chat.width + 80,
        relativeY: (CARD_DEFAULTS.ai_chat.height - sizeFromRatio(3 / 4).height) / 2,
        ...sizeFromRatio(3 / 4),
        data: {
          _locked: true,
          _label: "全身裂变",
          _description: "基于姿势灵感与参考图生成全身变体",
          content: "",
          size: "3:4",
        },
      },
    ],
    connections: [
      { sourceIndex: 0, targetIndex: 1 },
      { sourceIndex: 0, targetIndex: 2 },
      { sourceIndex: 1, targetIndex: 2 },
    ],
  },
];
